version: "3.8"

name: kreastol-reloaded

services:
  kreastol-app:
    image: kreastol-reloaded:1.5
    ports:
      - "8888:3000"
  db:
    container_name: psql
    restart: always
    image: psql
    build:
      context: ./db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234  # To be moved to environment file
      - POSTGRES_DATABASE=testdb
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - psql-pgql
  graphql:
    container_name: pgql
    restart: always
    image: graphile/postgraphile
    depends_on:
      - db
    expose:
      - 5000
    ports:
      - "5000:5000"
    command: ["--connection", "postgres://postgres:1234@db:5432/testdb", "--host", "0.0.0.0", "--port", "5000", "--schema", "testschema"]
    links:
      - db
    networks:
      - psql-pgql

networks:
  psql-pgql:

volumes:
  pgdata: